### ISSUE TITLE
Create receipt by commands vs. pdf

### ISSUE THREAD

**Issue by peragethemte** [star-micronics/StarPRNT-SDK-iOS-Swift#14]
Hi,

I'm developing a POS iOS application and have created a pdf receipt. I haven't yet added the Star SDK, but about to now. Can someone with experience give some advice between creating the receipt by commands vs just export a pdf receipt to the printer for printout?

**Comment by bandit-ibayashi** [comment]
We are afraid we have not responded this issue for a long time.

If you already have a POS application that produces receipts in PDF format, using [PassPRNT](https://apps.apple.com/us/app/star-passprnt/id979827520) app instead of this SDK will minimize integration.
We have an [SDK](https://github.com/star-micronics/star-passprnt-sdk-ios) for PassPRNT that makes it relatively easy to print PDFs by using a URL scheme to implement application integration.

If application transitions are not preferred, the PDF may be turned into a raster image and printed using the [appendBitmap](https://www.star-m.jp/products/s_print/sdk/starprnt_sdk/manual/ios_swift/en/api_starioext_i_command_builder.html#icommandbuilder-appendbitmap) method. We do not provide an API for creating image data from PDF, but it seems to be a common method.

Thanks,
