### ISSUE TITLE
Support SPM for iOS install

### ISSUE THREAD

**Issue by michaelosity** [star-micronics/StarPRNT-SDK-iOS-Swift#2]
Xcode now has SPM as it's package manager. It would be extremely useful to have support for SPM.

**Comment by bandit-ibayashi** [comment]
@michaelosity I am sorry for the late response. And thanks for your post to the issue. Your request was understood.

**Comment by michaelosity** [comment]
Another benefit of this change would be that this repo could support running in the iOS simulator for the new Mac M1s.

**Comment by frizzle** [comment]
SPM support will make it much easier to use your framework.

**Comment by tmykhaylovsky** [comment]
Starting to work on Bluetooth integration with StarMicronics devices.

SPM support would be much appreciated. Otherwise will have to play around with Podfiles and we've been able to avoid them thus far.

**Comment by sammcewan** [comment]
At a minimum can we please get the frameworks provided as XCFrameworks?

**Comment by nickdnk** [comment]
Bump. SPM much desired.

**Comment by helperbug** [comment]
Wrapping the XCFramework in an SPM would be very helpful

**Comment by bandit-ibayashi** [comment]
It has been changed to the **xcframework** format since [`StarIO`](https://github.com/star-micronics/StarPRNT-SDK-iOS-Swift/tree/master/software/libs/StarIO.xcframework) 2.10.0 and [`StarIO_Extention`](https://github.com/star-micronics/StarPRNT-SDK-iOS-Swift/tree/master/software/libs/StarIO_Extension.xcframework) 1.17.0. We understood it is necessary to be at least xcframework for SPM to be used.

We are afraid we do not plan to support SPM in StarIO (StarPRNT SDK), as we are supporting SPM in its successor StarIO10 (StarXpand SDK). We much appreciate you understanding.
