### ISSUE TITLE
pod install fails, 403 server failed to authenticate the request

### ISSUE THREAD

**Issue by tom-kraak9** [star-micronics/StarPRNT-SDK-iOS-Swift#22]
## Description
When I run the command pod install it fails with the following output in the terminal:

Installing StarIO (2.8.1)

[!] Error installing StarIO
[!] /usr/bin/curl -f -L -o /var/folders/sl/jfdrtpvj5ls7w127r92xqrmw0000gn/T/d20230106-52611-ytbmtj/file.zip https://libraryfilesstorage.blob.core.windows.net/ios/StarIO/2.8.1/StarIO.zip?sv=2019-02-02&si=TechSalesSupp&sr=c&sig=kkD24MYypOKNgnika6m1dHueNNbGz%2Bk0WQ8%2BuYO%2B0TM%3D --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.11.2 cocoapods-downloader/1.5.1'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

**Comment by bandit-ibayashi** [comment]
@tom-kraak9 Would it be possible to use the latest version of StarIO? There is backward compatibility between 2.8.1 and 2.9.0.
https://github.com/star-micronics/StarPRNT-SDK-iOS-Swift/blob/82abd91c5e4c30cd935507ee5fc0a59b654d84dc/SDK/Podfile#L10

This is not available at this time due to some problems with the upload procedure and because we have not found a way to update the URL for the relevant version. Since StarIO 2.8.1 has been out for some time, we would like you to use its latest version, 2.9.0.

Thank you for your understanding.

**Comment by tom-kraak9** [comment]
> @tom-kraak9 Would it be possible to use the latest version of StarIO? There is backward compatibility between 2.8.1 and 2.9.1.
> 
> https://github.com/star-micronics/StarPRNT-SDK-iOS-Swift/blob/82abd91c5e4c30cd935507ee5fc0a59b654d84dc/SDK/Podfile#L10
> 
Updating to the newest version indeed resolved the issue. Thanks!
