### ISSUE TITLE
iPadOS 16.5

### ISSUE THREAD

**Issue by DaveTTS** [star-micronics/StarPRNT-SDK-iOS-Swift#24]
Hi there

In the recently launched iPadOS 16.5, there were some changes to the Bluetooth management for iPadOS apps.  

As a result, if a user tries to run two or more scanning apps then the bluetooth connection stops working and devices such as star devices refuse to re-connect.

Most SDKs have been updated to reflect the change in iPadOS 16.5, however this appears to not be the case on this SDK.  Can you advise if and when you intend to deal with this iPadOS 16.5 bluetooth management issue?

Note that this issue only happens on iPadOS and does not affect iOS.

**Comment by bandit-ibayashi** [comment]
@DaveTTS Thank you for your contribution. 
Could you please fill in our Issue template so that we can get a more complete picture of the events you are facing and confirm this issue?

--- 
## Description
A clear and concise description of what a bug is.

## Your device where the bug occurs 
 - Device: 
    *e.g. iPhone 13*
 - OS:
    *e.g. iOS 15.0*
 - Browser: 
    *e.g. Safari*
 - Version
    *e.g. 22*

## Your printer
- Model Names:
    *e.g. mC-Print3*
- Firmware Version:
    *e.g. 3.5*
- Interface:
    *e.g. Ethernet*

## Your development environment
The result of executing the command `ver` on Windows, `sw_vers` on macOS, `uname –a` on Linux, or these equivalent commands.

## To Reproduce
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

## Expected behavior
A clear and concise description of what you expected to happen.

## Screenshots
If applicable, add screenshots to help explain your problem.

## Additional context
Add any other context about the bug here.

**Comment by bandit-ibayashi** [comment]
As this Issue has not moved for a long time, and since a new iOS has been released and our checks with them have not caused any problems, this Issue is closed at this time.
If you continue to experience problems, please let us know.
