### ISSUE TITLE
Please create a swift package for the StarPrint iOS framework

### ISSUE THREAD

**Issue by randeep-ot** [star-micronics/StarPRNT-SDK-iOS-Swift#29]
## Description
Please create a swift package for the StarPrint iOS framework. This will simplify integrating SDK via Xcode

**Comment by bandit-ibayashi** [comment]
This is the same issue (request) #2 and #19 .

We do not have a plan to support SPM as the framework included in the successor StarXpand SDK supports it and StarIO supports cocoapods as a package management tool.
If you are starting a new implementation, we recommend that you use the StarXpand SDK for iOS.

And it has been changed to the xcframework format since [StarIO](https://github.com/star-micronics/StarPRNT-SDK-iOS-Swift/tree/master/software/libs/StarIO.xcframework) 2.10.0 and [StarIO_Extention](https://github.com/star-micronics/StarPRNT-SDK-iOS-Swift/tree/master/software/libs/StarIO_Extension.xcframework) 1.17.0. We understood it is necessary to be at least xcframework for SPM to be used.

Thank you for your understanding.

**Comment by randeep-ot** [comment]
Thanks for the response @bandit-ibayashi
Should we be migrating to StarXpand? Is there a migration guide?
Are there any plans of deprecating StarIO in the near future?
