### ISSUE TITLE
Rotate ticket failed after enable "180 Rotation"

### ISSUE THREAD

**Issue by WenzhaoTan-Chowbus** [star-micronics/StarPRNT-SDK-iOS-Swift#7]
Printer Mode: MCP31 (STR-001)
Firmware Version: 3.4

I set up my ticket using ISCBBuilder, and I want to rotate my ticket to 180, so I enable the "180 Rotation" by mc_Print Utility.
But the ticket is not displayed correctly if it is very long.
![441629858538_ pic_hd](https://user-images.githubusercontent.com/65152333/130716650-658a32f7-9730-4af6-9011-d21fbc15d186.jpg)

**Comment by gare-bear** [comment]
@WenzhaoTan-Chowbus approximately how long is your receipt? Also are you using Double-Byte mode to print the Asian characters?

**Comment by bandit-ibayashi** [comment]
180˚ Inversion Function is worked for the print data that fits in the image buffer length. When inversion 180 degrees, the data must be buffered once in the printer because it is printed from the end of the data. The buffer for this is finite, and if it is exceeded, this feature cannot be used.

Thank you for your understanding.
