### ISSUE TITLE
Add support for TUP* models (open frame kiosk printers)

### ISSUE THREAD

**Issue by Yrouel** [star-micronics/StarPRNT-SDK-iOS-Swift#8]
I understand it might not be a typical scenario to connect an iOS device to a printer meant to be mounted inside a kiosk but they share the same interface boards with their standalone siblings and it would be nice to also have these models (TUP900, TUP500, TUP400) supported by the official iOS apps

**Comment by gare-bear** [comment]
@Yrouel Thanks for the feedback! 

An iOS device presents some challenges when considering some of the common requirements for a Kiosk, but it's not impossible. First, most Kiosks require a USB connected printer which is not easy on iOS due to MFi certification requirements. On a side note, Bluetooth printers must also be MFi certified. Today we have some MFi certified USB printers but not within our Kiosk lineup. 

The most viable option is an **Ethernet** connection, which leads into **which printers support a LAN connection?**

I think the TUP400 has been discontinued in most of the Star territories, but we could consider adding support for its successor; the TUP500.

On the other hand, the TUP900 has some compatibility issues with our HE07/08 Network interface card, so that prevents us from easily supporting in our StarPRNT SDK for iOS.

We see much more success on Android, where the built in USB port on the tablet/ phone/ etc, is much easier to interface with.

**Comment by gare-bear** [comment]
@Yrouel if you're working a project using our Kiosk printers, we'd love to hear about it.
